"""
Experiment execution sandbox for Discovery Zero.

Provides a hardened Python execution environment for mathematical
experiments generated by the LLM.  Features:

  - Allowlist-based import restriction (no os, subprocess, network, etc.)
  - Resource limits via resource.setrlimit (memory + CPU time)
  - Result caching via SHA-256 of (code, inputs)
  - Persistent state dictionary across related experiments
  - Structured SandboxResult output
  - Timeout enforcement via threading

This module extracts and significantly enhances the experiment execution
logic previously embedded in the orchestrator.
"""

from __future__ import annotations

import hashlib
import io
import json
import logging
import math
import sys
import threading
import time
import traceback
from contextlib import redirect_stdout, redirect_stderr
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


# ------------------------------------------------------------------ #
# Safe import allowlist                                                #
# ------------------------------------------------------------------ #

SAFE_IMPORTS: frozenset[str] = frozenset({
    # Standard library — safe math/data manipulation
    "math", "cmath", "random", "json", "statistics",
    "itertools", "functools", "fractions", "decimal", "collections",
    "hashlib", "re", "string", "operator", "bisect", "heapq",
    "array", "struct", "copy", "pprint", "textwrap",
    "numbers", "typing", "dataclasses", "enum", "abc",
    # Scientific computing
    "numpy", "scipy", "sympy", "mpmath",
    # numpy sub-modules
    "numpy.linalg", "numpy.fft", "numpy.random", "numpy.polynomial",
    # scipy sub-modules
    "scipy.linalg", "scipy.optimize", "scipy.stats", "scipy.special",
    "scipy.integrate", "scipy.signal",
    # sympy sub-modules
    "sympy.core", "sympy.solvers", "sympy.geometry", "sympy.ntheory",
    "sympy.combinatorics", "sympy.series", "sympy.matrices",
    # Internal — allow importing discovery_zero graph for analysis
    # (disabled by default; enable per sandbox run)
})

# Packages that should NEVER be imported regardless of allowlist
BLOCKED_IMPORTS: frozenset[str] = frozenset({
    "os", "sys", "subprocess", "socket", "http", "urllib",
    "ftplib", "smtplib", "telnetlib", "poplib", "imaplib",
    "shutil", "tempfile", "glob", "pathlib", "pickle", "shelve",
    "ctypes", "cffi", "importlib", "_imp", "builtins",
    "threading", "multiprocessing", "concurrent",
    "signal", "resource", "gc",
})


# ------------------------------------------------------------------ #
# Configuration                                                        #
# ------------------------------------------------------------------ #

@dataclass
class SandboxConfig:
    timeout_seconds: int = 120
    memory_limit_mb: int = 512
    cpu_time_limit: int = 60
    max_output_chars: int = 50_000
    allow_extra_imports: frozenset[str] = field(default_factory=frozenset)
    enable_resource_limits: bool = True


# ------------------------------------------------------------------ #
# Result                                                               #
# ------------------------------------------------------------------ #

@dataclass
class SandboxResult:
    success: bool
    stdout: str
    stderr: str
    parsed_json: Optional[Any]
    execution_time_ms: float
    error_message: str = ""
    timed_out: bool = False

    def to_dict(self) -> Dict[str, Any]:
        return {
            "success": self.success,
            "stdout": self.stdout[:2000],
            "stderr": self.stderr[:1000],
            "parsed_json": self.parsed_json,
            "execution_time_ms": round(self.execution_time_ms, 1),
            "error_message": self.error_message,
            "timed_out": self.timed_out,
        }


# ------------------------------------------------------------------ #
# Safe builtins + restricted import                                    #
# ------------------------------------------------------------------ #

def _make_restricted_import(
    allowed: frozenset[str],
    blocked: frozenset[str],
) -> Any:
    """Return a __import__ function that enforces the allowlist."""
    import importlib

    def restricted_import(
        name: str,
        globals: Any = None,
        locals: Any = None,
        fromlist: Any = (),
        level: int = 0,
    ) -> Any:
        base = name.split(".")[0]
        if base in blocked:
            raise ImportError(f"Import of '{name}' is not permitted in sandbox.")
        if base not in allowed and name not in allowed:
            raise ImportError(
                f"Import of '{name}' is not in the allowlist. "
                f"Available: {sorted(allowed)}"
            )
        return importlib.import_module(name)

    return restricted_import


def _make_safe_globals(
    config: SandboxConfig,
    persistent_state: Optional[Dict[str, Any]],
) -> Dict[str, Any]:
    """Build a restricted __globals__ dict for exec()."""
    allowed = SAFE_IMPORTS | (config.allow_extra_imports or frozenset())

    # Build minimal safe builtins
    import builtins as _builtins
    safe_builtin_names = {
        "abs", "all", "any", "bin", "bool", "bytes", "callable",
        "chr", "complex", "dict", "divmod", "enumerate", "filter",
        "float", "format", "frozenset", "getattr", "hasattr", "hash",
        "hex", "id", "int", "isinstance", "issubclass", "iter",
        "len", "list", "map", "max", "min", "next", "object", "oct",
        "ord", "pow", "print", "property", "range", "repr", "reversed",
        "round", "set", "setattr", "slice", "sorted", "staticmethod",
        "str", "sum", "super", "tuple", "type", "vars", "zip",
        "True", "False", "None",
        "Exception", "ValueError", "TypeError", "KeyError",
        "IndexError", "AttributeError", "RuntimeError", "StopIteration",
        "NotImplementedError", "ArithmeticError", "ZeroDivisionError",
        "OverflowError", "ImportError", "AssertionError",
    }
    safe_builtins = {
        name: getattr(_builtins, name)
        for name in safe_builtin_names
        if hasattr(_builtins, name)
    }
    safe_builtins["__import__"] = _make_restricted_import(allowed, BLOCKED_IMPORTS)

    safe_globals: Dict[str, Any] = {
        "__builtins__": safe_builtins,
        "__name__": "__sandbox__",
    }
    if persistent_state:
        safe_globals["_state"] = dict(persistent_state)
    else:
        safe_globals["_state"] = {}

    return safe_globals


# ------------------------------------------------------------------ #
# Resource limits (Unix only)                                          #
# ------------------------------------------------------------------ #

def _apply_resource_limits(config: SandboxConfig) -> None:
    """Apply memory and CPU time limits using resource module."""
    if not config.enable_resource_limits:
        return
    try:
        import resource

        # Virtual address space limit (memory)
        mem_bytes = config.memory_limit_mb * 1024 * 1024
        soft, hard = resource.getrlimit(resource.RLIMIT_AS)
        new_soft = min(mem_bytes, hard) if hard != resource.RLIM_INFINITY else mem_bytes
        resource.setrlimit(resource.RLIMIT_AS, (new_soft, hard))

        # CPU time limit
        cpu_soft, cpu_hard = resource.getrlimit(resource.RLIMIT_CPU)
        new_cpu = min(config.cpu_time_limit, cpu_hard) if cpu_hard != resource.RLIM_INFINITY else config.cpu_time_limit
        resource.setrlimit(resource.RLIMIT_CPU, (new_cpu, cpu_hard))

    except Exception as exc:
        logger.debug("Could not set resource limits: %s", exc)


# ------------------------------------------------------------------ #
# Core execution                                                       #
# ------------------------------------------------------------------ #

def _exec_in_thread(
    code: str,
    safe_globals: Dict[str, Any],
    stdout_buffer: io.StringIO,
    stderr_buffer: io.StringIO,
    config: SandboxConfig,
    result_container: List[Optional[Exception]],
) -> None:
    """Target function for the sandbox thread."""
    _apply_resource_limits(config)
    try:
        with redirect_stdout(stdout_buffer), redirect_stderr(stderr_buffer):
            exec(compile(code, "<sandbox>", "exec"), safe_globals)
        result_container[0] = None
    except Exception as exc:
        result_container[0] = exc


def execute_sandboxed(
    code: str,
    *,
    config: Optional[SandboxConfig] = None,
    persistent_state: Optional[Dict[str, Any]] = None,
) -> SandboxResult:
    """
    Execute Python code in a restricted sandbox.

    Args:
        code: Python source code to execute.
        config: Sandbox configuration.  Uses defaults if None.
        persistent_state: Dict that is available as `_state` in the code.
            The code can modify `_state` to persist results across calls.

    Returns:
        SandboxResult with stdout, parsed JSON (if any), timing info.
    """
    if config is None:
        config = SandboxConfig()

    safe_globals = _make_safe_globals(config, persistent_state)
    stdout_buf = io.StringIO()
    stderr_buf = io.StringIO()
    result_container: List[Optional[Exception]] = [None]

    t0 = time.monotonic()

    thread = threading.Thread(
        target=_exec_in_thread,
        args=(code, safe_globals, stdout_buf, stderr_buf, config, result_container),
        daemon=True,
    )
    thread.start()
    thread.join(timeout=config.timeout_seconds)

    elapsed_ms = (time.monotonic() - t0) * 1000
    timed_out = thread.is_alive()

    stdout_raw = stdout_buf.getvalue()[:config.max_output_chars]
    stderr_raw = stderr_buf.getvalue()[:config.max_output_chars]

    if timed_out:
        return SandboxResult(
            success=False,
            stdout=stdout_raw,
            stderr=stderr_raw,
            parsed_json=None,
            execution_time_ms=elapsed_ms,
            error_message=f"Execution timed out after {config.timeout_seconds}s",
            timed_out=True,
        )

    exc = result_container[0]
    if exc is not None:
        tb = traceback.format_exception(type(exc), exc, exc.__traceback__)
        err_str = "".join(tb)[-2000:]
        return SandboxResult(
            success=False,
            stdout=stdout_raw,
            stderr=err_str,
            parsed_json=None,
            execution_time_ms=elapsed_ms,
            error_message=str(exc)[:500],
        )

    # Try to extract JSON from stdout
    parsed_json: Optional[Any] = None
    stdout_text = stdout_raw.strip()
    if stdout_text:
        # Try last line, then whole output
        for candidate in [stdout_text.splitlines()[-1], stdout_text]:
            try:
                parsed_json = json.loads(candidate)
                break
            except json.JSONDecodeError:
                pass
        if parsed_json is None:
            # Scan for JSON object/array
            import re as _re
            match = _re.search(r"[\[{].*[\]}]", stdout_text, _re.DOTALL)
            if match:
                try:
                    parsed_json = json.loads(match.group(0))
                except json.JSONDecodeError:
                    pass

    # Persist updated _state
    if persistent_state is not None:
        updated = safe_globals.get("_state", {})
        if isinstance(updated, dict):
            persistent_state.clear()
            persistent_state.update(updated)

    return SandboxResult(
        success=True,
        stdout=stdout_raw,
        stderr=stderr_raw,
        parsed_json=parsed_json,
        execution_time_ms=elapsed_ms,
    )


# ------------------------------------------------------------------ #
# Result cache                                                         #
# ------------------------------------------------------------------ #

class ExperimentCache:
    """
    Disk-backed cache for sandbox results.

    Keys are SHA-256 of (code + input_hash).  Results are stored as JSON
    files under cache_dir.  This avoids re-running identical experiments
    during iterative exploration.
    """

    def __init__(self, cache_dir: Path) -> None:
        self._dir = cache_dir
        self._dir.mkdir(parents=True, exist_ok=True)

    @staticmethod
    def make_key(code: str, inputs: str = "") -> str:
        digest = hashlib.sha256((code + inputs).encode("utf-8")).hexdigest()
        return digest[:32]

    def get(self, key: str) -> Optional[SandboxResult]:
        path = self._dir / f"{key}.json"
        if not path.exists():
            return None
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
            return SandboxResult(
                success=data["success"],
                stdout=data.get("stdout", ""),
                stderr=data.get("stderr", ""),
                parsed_json=data.get("parsed_json"),
                execution_time_ms=data.get("execution_time_ms", 0.0),
                error_message=data.get("error_message", ""),
                timed_out=data.get("timed_out", False),
            )
        except Exception as exc:
            logger.debug("Cache read error for %s: %s", key, exc)
            return None

    def put(self, key: str, result: SandboxResult) -> None:
        path = self._dir / f"{key}.json"
        try:
            path.write_text(
                json.dumps(result.to_dict(), ensure_ascii=False, indent=2),
                encoding="utf-8",
            )
        except Exception as exc:
            logger.debug("Cache write error for %s: %s", key, exc)

    def invalidate(self, key: str) -> bool:
        path = self._dir / f"{key}.json"
        if path.exists():
            path.unlink()
            return True
        return False

    def clear(self) -> int:
        """Remove all cached results.  Returns number deleted."""
        count = 0
        for f in self._dir.glob("*.json"):
            try:
                f.unlink()
                count += 1
            except OSError:
                pass
        return count
